---
###############################################################################
#
# tasks/configure-google-ntp.yml
#
# Task for configure google ntp 
#
###############################################################################

# Install config file
- name: Configure Google NTP and backup
  template:
    src: ntp.conf.j2 
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: restart ntp

