---
###############################################################################
#
# tasks/create-user.yml
#
# Create the user account
#
# HINT: The user module does not allow the password to be plaintext
# Try the value "password" on the user created....super secure :) 
###############################################################################

- name: Create group
  group:
    name: "{{ username }}"
    gid: "{{ gid }}"
    system: no
    state: present

- name: Create user
  user:
    name: "{{ username }}"
    comment: "{{ comment }}"
    uid: "{{ uid }}"
    create_home: yes
    home: '{{ homedir }}'
    password: $6$osJfb1B67lQrn7MY$OQJCq6f1WiEzxHEB6mH6IMoB1aWUZDQ2tFPKlhU/UrPraOQkOP0j/cLwoJuFuHMd8ueErRlIkdtPqCsvdrmCG.
    shell: /bin/bash
    system: no
    group: "{{ username }}"
  ignore_errors: yes


