---
###############################################################################
#
# tasks/packages.yml
#
# Task for base-packages
#
###############################################################################

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_packages }}"

