---
# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# A list of users who will be added to the docker group.
docker_users: [vagrant]