---
##################################################################################
#
# playbooks/example-role.yml
#
#
##################################################################################

- name: example-role
  hosts: all
  become: yes

  tasks:

    - include_role:
        name: ../roles/example-role

