---
  - name: vars_playbook
    hosts: webserver
    remote_user: vagrant
    become: yes
    become_user: root

    vars:
      user: admin

    tasks:

      - name: Add the user 'admin' with a bash shell, appending the group 'adm'
        user:
          name: "{{ user }}"
          shell: /bin/bash
          groups: adm
          append: yes
   
      - name: Gathering ansible facts 
        debug:
          msg: Users found in adm group "{{ohai_etc.group.adm.members}}"
