---
###############################################################################
#
# defaults/main.yml
#
# defaults file for example role
#
###############################################################################

#List of packages to install 
base_packages:
  - nmap
  - iperf3
  - tree
  - vim
  - ntp

#Creating our administrator user
username: admin
homedir: /home/admin
uid: 2020
gid: 2020
comment: admin user

#Google NTP Settings
google:
  ntp:
    server1: time1.google.com iburst
    server2: time2.google.com iburst
    server3: time3.google.com iburst
    server4: time4.google.com iburst
